[pytest]
testpaths =
    tests
    api
    unit

python_files =
    test_*.py

python_classes =
    Test*

python_functions =
    test_*

markers =
    smoke: critical tests executed for quick validation
    regression: complete regression suite
    api: API automation tests
    ui: UI automation tests
    unit: unit tests

addopts =
    -v
    --html=reports/report.html
    --self-contained-html